### ISSUE TITLE
No local user

### ISSUE THREAD

**Issue by woopstar** [bytewareio/iam_ssh_authorizedkeys#7]
How do you handle if the local user does not exist on the machine?

**Comment by mikenowak** [comment]
Hi @woopstar, we don't handle this - and we assume that the users are created by another means. Let me know if you need more info.

**Comment by woopstar** [comment]
We kinda made the same service at our company, just for privacyIDEA. Yet we want to face the issue where local users does not exist and then create them on the fly . 

The issue for us is when we get new people, we have to create a local account on +1000 servers.
